### PR TITLE
Add support to elixir 1.1.0

### PR DESCRIPTION
**Pull request by dukex**

### CODE REVIEW

**Comment by devinus** [comment]
Wait, does `~> 1.0` not support 1.1?

**Comment by dukex** [comment]
No :disappointed:, I'm receiving a warning about elixir version

I check on http://jubianchi.github.io/semver-check/ and the result was:
```
~> 1.0 is a range (tilde) constraint. It means that it will match several versions.

In fact, the current constraint will be satisfied by any version matching >=> 1.0.0.

Composer handles tilde-range differently. Your constraint will translate to >=> 1.0.0.

This constraint does not provide an upper bound which means you will probably get unexpected BC break.

Given the constraint you entered, you will get:

    The next patch releases which will fix bugs
```

**Comment by devinus** [comment]
This is weird. I definitely don't get any error. Could you screenshot the error it gives you?

**Comment by devinus** [comment]
http://elixir-lang.org/docs/stable/elixir/Version.html

According to this, `~> 2.0` will match `>= 2.0 or < 3.0`.

**Comment by ericmj** [comment]
`~>` definitely works like @devinus says.

@dukex Are you sure you are using the latest version of Poison (v1.5.0)? You can check in your `mix.lock` file what version you are using and update with `mix deps.update poison` if your and your dependencies' version requirements on poison allows it.

**Comment by dukex** [comment]
Sorry the delay, follow the warning 
screenshot from 2015-10-02 22 37 30

**Comment by dukex** [comment]
@devinus  and @ericmj Thanks, the problems was the poison version

**Pull request closed without merging**
