### PR TITLE
Implement derivable Poison.Encoder

### PR DESCRIPTION
**Pull request by devinus**
@josevalim

### CODE REVIEW

**Comment by devinus** [comment]
Closes https://github.com/devinus/poison/issues/38.

**Comment by josevalim** [comment]
This looks great. It would be really neat though if you supported the `:only` option:

```elixir
@derive {Poison.Encoder, only: [:name, :this, :that]}
```

If `:only` is given, you'd need to do `Map.take/2` instead of `Map.from_struct`, but it should work just as fine.

**Comment by devinus** [comment]
Nice, I'll add that.

**Comment by devinus** [comment]
@josevalim Question: where is `Map.take` defined?

**Comment by hunterboerner** [comment]
Any benchmarks showing how much faster this is?

**Comment by devinus** [comment]
@hunterboerner The in-repo benchmarks contain one for it. It's almost as fast as encoding a raw map.

**Pull request merged**
