### PR TITLE
Add support for Elixir v1.3 Calendar data types

### PR DESCRIPTION
**Pull request by josevalim**
I had some free time to solve #77. @devinus please check if those implementations actually make sense JSON-encoding wise.

### CODE REVIEW

**Comment by devinus** [comment]
Shouldn't we `Code.ensure_loaded?(Calendar)` for the actual protocol implementation?

**Comment by josevalim** [comment]
@devinus no, we should be fine. We can implement protocols without the types being available and I don't think any of the datetime libraries defines those types. The CI failure seems to be Erlang 17.3 related.

**Comment by devinus** [comment]
@josevalim I'd like to do it anyway, because I think some people have defined their own `Date` and `DateTime` structs. Thoughts?

**Comment by devinus** [comment]
Also, this is really great. Excited to see `Calendar` in core now.

**Comment by josevalim** [comment]
@devinus we could do it too but it also has false positives like the Calendar library that defines a Calendar module. It is completely up to you but I would go ahead with this change and if people define a DateTime type, they will have to fix their code when migrating to v1.3 anyway.

**Comment by devinus** [comment]
> it also has false positives like the Calendar library

True.

**Comment by devinus** [comment]
@ericmj Any idea what's up with 17.3 wrt Hex here: https://travis-ci.org/devinus/poison/jobs/135435014

**Comment by josevalim** [comment]
@devinus it is an issue with the SSL that ships in the Erlang distribution. The best option is to not use 17.3 but we will improve Hex to provide a better error report.

**Comment by devinus** [comment]
@josevalim That's what I figured, but when the new HTTPS Hex stuff was announced it was recommended to use 17.3, so it seems weird that it changed?

**Comment by josevalim** [comment]
Btw, v1.3 is coming out today, so a new Poison release is likely very welcome. :D

**Pull request merged**
